# Generated by Django 4.1.5 on 2023-04-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.TextField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')]),
        ),
        migrations.AlterField(
            model_name='question',
            name='maximum_marks',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
