# Generated by Django 4.1.5 on 2023-04-19 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_question_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizprofile',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.question'),
        ),
    ]
