# Generated by Django 4.1.5 on 2023-04-19 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quizprofile_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizprofile',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.category'),
        ),
    ]
