# Generated by Django 4.1.5 on 2023-05-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quizprofile_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=50),
        ),
    ]
