# Generated by Django 4.1.5 on 2023-05-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_remove_question_difficulty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='question',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='user_quiz',
        ),
        migrations.RemoveField(
            model_name='selectedchoice',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='selectedchoice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='selectedchoice',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userquiz',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='userquiz',
            name='user',
        ),
        migrations.AddField(
            model_name='quizprofile',
            name='bad_performance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizprofile',
            name='good_performance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='AttemptedQuestion',
        ),
        migrations.DeleteModel(
            name='QuizQuestion',
        ),
        migrations.DeleteModel(
            name='SelectedChoice',
        ),
        migrations.DeleteModel(
            name='UserQuiz',
        ),
    ]
