# Generated by Django 4.1.5 on 2023-05-06 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0008_alter_choice_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizprofile',
            name='has_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizprofile',
            name='times_taken',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('score', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Score')),
                ('passed', models.BooleanField(default=False, verbose_name='Passed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
