# Generated by Django 4.1.5 on 2023-05-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_quizprofile_has_failed_quizprofile_times_taken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizprofile',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizprofile',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
