# Generated by Django 4.1.5 on 2023-05-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_quizprofile_end_time_quizprofile_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizprofile',
            name='bad_performance',
        ),
        migrations.RemoveField(
            model_name='quizprofile',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='quizprofile',
            name='good_performance',
        ),
        migrations.RemoveField(
            model_name='quizprofile',
            name='has_failed',
        ),
        migrations.RemoveField(
            model_name='quizprofile',
            name='start_time',
        ),
        migrations.AddField(
            model_name='quizprofile',
            name='recent_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Recent Score'),
        ),
    ]
